FROM ubuntu:18.04
# RUN apt-get update && apt-get -y upgrade && \
#     apt-get -f -y install curl apt-transport-https lsb-release gnupg python3-pip python-pip && \
#     curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.asc.gpg && \
#     CLI_REPO=$(lsb_release -cs) && \
#     echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ ${CLI_REPO} main" \
#     > /etc/apt/sources.list.d/azure-cli.list && \
#     apt-get update && \
#     apt-get install -y azure-cli && \
#     rm -rf /var/lib/apt/lists/*